name: Linting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6.0.1

      - uses: actions/setup-node@v6.1.0
        with:
          node-version-file: '.node-version'

      - name: Setup
        run: |
          brew install swiftlint
          swiftlint version
          npm ci

      - name: Linting
        run: |
          npm test
          npm run lint:swift

  auto-merge:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Automatically merge dependabot upgrades
        uses: fastify/github-action-merge-dependabot@v3.11.2
        with:
          target: minor
